version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data  # コンテナ内の /var/lib/postgresql/data に、postgres_data という名前のDockerボリュームをマウント
    ports:
      - "5432:5432"  # ローカル→コンテナのポートマッピング

  backend:
    build: ./backend  # backendディレクトリのDockerfileからビルド
    env_file: .env # 環境変数ファイルを読み込む
    ports:
      - "8080:8080"  # Spring Bootアプリを公開
    depends_on:
      - db  # dbが起動してからbackendを起動
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true  # Reactのライブリロード対策（Macで有効）
    volumes:
      - ./frontend:/app
      - /app/node_modules # ここだけはDocker内に閉じておく


volumes:
  db-data:  # ボリュームを定義し、DBデータを永続化。コンテナを消してもデータが残る。
